NUMPY:

Array creation and properties:

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
b = range(15)

In [3]:
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
range(0, 15)


In [4]:
a =  np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

2
(2, 5)
10
int32
4
<class 'numpy.ndarray'>


In [6]:
help(a)

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

In [7]:
b = np.array([1.0, 2.0, 3.0, 4.0])
print(b)
print(b.dtype)
print(type(b))

[1. 2. 3. 4.]
float64
<class 'numpy.ndarray'>


In [8]:
c = np.eye(10)
dtype = np.float64
c

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

Linspace ang Logspace:

In [9]:
d = np.linspace(-1, 2, 10, endpoint = True)
print(d)

[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.          1.33333333  1.66666667  2.        ]


In [10]:
e = np.logspace(-1, 2, 10, endpoint=True, base=5)
print(e)

[ 0.2         0.34199519  0.58480355  1.          1.70997595  2.92401774
  5.          8.54987973 14.62008869 25.        ]


In [11]:
help(np.logspace)

Help on function logspace in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.
    
    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boolean, optional
        If true, `stop` is the last sample. Otherwise, 

In [12]:
f = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
f

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

Array Operations:

In [13]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
a*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [15]:
a + a + a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [16]:
a * a

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [17]:
print(a)
b = a.transpose()
b

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [18]:
a @ b

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [19]:
print(a)
a.sum(axis=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([ 3, 12, 21])

In [20]:
a.sum()

36

In [21]:
print(a.min(), a.max())

0 8


Universal functions: 

In [22]:
b = a * np.pi / 12.0
print(b)

[[0.         0.26179939 0.52359878]
 [0.78539816 1.04719755 1.30899694]
 [1.57079633 1.83259571 2.0943951 ]]


In [23]:
c = np.cos(b)
print(c)

[[ 1.00000000e+00  9.65925826e-01  8.66025404e-01]
 [ 7.07106781e-01  5.00000000e-01  2.58819045e-01]
 [ 6.12323400e-17 -2.58819045e-01 -5.00000000e-01]]


In [24]:
c = np.sin(b)
print(c)

[[0.         0.25881905 0.5       ]
 [0.70710678 0.8660254  0.96592583]
 [1.         0.96592583 0.8660254 ]]


In [25]:
d = b + c
print(d)

[[0.         0.52061843 1.02359878]
 [1.49250494 1.91322295 2.27492277]
 [2.57079633 2.79852154 2.96042051]]


Array Slicing: Accessing Subarrays

In [26]:
num = np.arange(1000)
num

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [27]:
evennum = num[0:995:2]
print(evennum)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [28]:
oddnum = num[0:995:3]
print(oddnum)

[  0   3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51
  54  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105
 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159
 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213
 216 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267
 270 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321
 324 327 330 333 336 339 342 345 348 351 354 357 360 363 366 369 372 375
 378 381 384 387 390 393 396 399 402 405 408 411 414 417 420 423 426 429
 432 435 438 441 444 447 450 453 456 459 462 465 468 471 474 477 480 483
 486 489 492 495 498 501 504 507 510 513 516 519 522 525 528 531 534 537
 540 543 546 549 552 555 558 561 564 567 570 573 576 579 582 585 588 591
 594 597 600 603 606 609 612 615 618 621 624 627 630 633 636 639 642 645
 648 651 654 657 660 663 666 669 672 675 678 681 684 687 690 693 696 699
 702 705 708 711 714 717 720 723 726 729 732 735 73

In [29]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [30]:
a[3]

3

In [31]:
print(a[2:3])

[2]


In [32]:
print(a[2:4])

[2 3]


In [33]:
a[:]

array([0, 1, 2, 3, 4, 5])

Multidimensional Arrays:

In [34]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
a[1,2]

7

In [36]:
a[1,1]

6

In [37]:
a[0:2,0:2]

array([[0, 1],
       [5, 6]])

In [38]:
a[:,1]

array([1, 6])

In [39]:
a = a.flatten()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
for x in a:
    print(x)
a = np.arange(10).reshape(2,5)
a

0
1
2
3
4
5
6
7
8
9


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
for e in a.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9


In [42]:
help(a.flatten())

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

Copying Arrays:

In [43]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
b = a
b is a

True

In [45]:
b.shape = (2,5)
print(b)
a.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [46]:
b is a

True

In [47]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
a = np.arange(10)
c = a[:]
a.shape = (2,5)
print(a)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [49]:
c[1] = -1
print(a)
print(c)

[[ 0 -1  2  3  4]
 [ 5  6  7  8  9]]
[ 0 -1  2  3  4  5  6  7  8  9]


In [50]:
d = c[2:6]
d

array([2, 3, 4, 5])

In [51]:
d[:] = 0

In [52]:
print(a)
print(c)
print(d)

[[ 0 -1  0  0  0]
 [ 0  6  7  8  9]]
[ 0 -1  0  0  0  0  6  7  8  9]
[0 0 0 0]


In [53]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


In [54]:
d = a.copy()
d[:,:] = 0.0

print(a)
print(d)

[[ 0 -1  0  0  0]
 [ 0  6  7  8  9]]
[[0 0 0 0 0]
 [0 0 0 0 0]]


Boolean Indexing:

In [60]:
import numpy as np
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a[a > 4] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
a[a == 0] = -1
a

array([[-1,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [63]:
a == -1

array([[ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
a = np.arange(15).reshape(3,5)
a[np.logical_and(a > 3, a <= 9)] = 0.0
a

array([[ 0,  1,  2,  3,  0],
       [ 0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14]])

In [65]:
a > 4

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

Avoiding Loops:

In [69]:
M = 32
N = 64
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, M, endpoint=False)
y = np.linspace(ymin, ymax, N, endpoint=False)

print(x.shape)
print(y.shape)
y

(32,)
(64,)


array([0.      , 0.015625, 0.03125 , 0.046875, 0.0625  , 0.078125,
       0.09375 , 0.109375, 0.125   , 0.140625, 0.15625 , 0.171875,
       0.1875  , 0.203125, 0.21875 , 0.234375, 0.25    , 0.265625,
       0.28125 , 0.296875, 0.3125  , 0.328125, 0.34375 , 0.359375,
       0.375   , 0.390625, 0.40625 , 0.421875, 0.4375  , 0.453125,
       0.46875 , 0.484375, 0.5     , 0.515625, 0.53125 , 0.546875,
       0.5625  , 0.578125, 0.59375 , 0.609375, 0.625   , 0.640625,
       0.65625 , 0.671875, 0.6875  , 0.703125, 0.71875 , 0.734375,
       0.75    , 0.765625, 0.78125 , 0.796875, 0.8125  , 0.828125,
       0.84375 , 0.859375, 0.875   , 0.890625, 0.90625 , 0.921875,
       0.9375  , 0.953125, 0.96875 , 0.984375])

In [70]:
import time
import numpy as np
M = 32
N = 64

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0, 1.0, N, endpoint=False)

In [73]:
t0 = time.time()

g = np.zeros((M,N))
print(g)

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])

print(g)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.00306796  0.00613588 ...  0.18605515  0.18906866
   0.1920804 ]
 [ 0.          0.00613588  0.01227154 ...  0.365613    0.37131719
   0.37700741]
 ...
 [ 0.          0.08885355  0.17700422 ... -0.75520138 -0.69397146
  -0.62725182]
 [ 0.          0.09190896  0.18303989 ... -0.62005721 -0.54532499
  -0.4659765 ]
 [ 0.          0.0949635   0.18906866 ... -0.46325978 -0.37700741
  -0.28734746]]
time elapsed: 0.011399507522583008 s


In [77]:
x2d, y2d = np.meshgrid(x, y, indexing="ij")

print(x2d[:,0])
print(x2d[0,:])

print(y2d[:,0])
print(y2d[0,:])

print(x2d)

[0.      0.03125 0.0625  0.09375 0.125   0.15625 0.1875  0.21875 0.25
 0.28125 0.3125  0.34375 0.375   0.40625 0.4375  0.46875 0.5     0.53125
 0.5625  0.59375 0.625   0.65625 0.6875  0.71875 0.75    0.78125 0.8125
 0.84375 0.875   0.90625 0.9375  0.96875]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
[0.       0.015625 0.03125  0.046875 0.0625   0.078125 0.09375  0.109375
 0.125    0.140625 0.15625  0.171875 0.1875   0.203125 0.21875  0.234375
 0.25     0.265625 0.28125  0.296875 0.3125   0.328125 0.34375  0.359375
 0.375    0.390625 0.40625  0.421875 0.4375   0.453125 0.46875  0.484375
 0.5      0.515625 0.53125  0.546875 0.5625   0.578125 0.59375  0.609375
 0.625    0.640625 0.65625  0.671875 0.6875   0.703125 0.71875  0.734375
 0.75     

In [76]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0009963512420654297 s


Numpy Standard Data Types:

Array Concatenation and Splitting:

Concatenation of arrays:

In [78]:
x = np.array([1, 2, 3, 4])
y = np.array([4, 3, 2, 1])
np.concatenate([y,x])

array([4, 3, 2, 1, 1, 2, 3, 4])

In [79]:
z = [6, 8, 5]
print(np.concatenate([x, y, z]))

[1 2 3 4 4 3 2 1 6 8 5]


In [80]:
grid = np.array([[15, 25, 35],[45, 55, 65]])

In [81]:
np.concatenate([grid, grid])

array([[15, 25, 35],
       [45, 55, 65],
       [15, 25, 35],
       [45, 55, 65]])

In [83]:
np.concatenate([grid, grid], axis=1)

array([[15, 25, 35, 15, 25, 35],
       [45, 55, 65, 45, 55, 65]])

Splitting of arrays:

In [85]:
x = [2, 4, 5, 3, 6, 9, 4, 1, 8 , 7]
x1, x2, x3, x4 = np.split(x, [4, 6, 7])
print(x1, x2, x3, x4)

[2 4 5 3] [6 9] [4] [1 8 7]


In [86]:
grid = np.arange(20).reshape(4,5)
grid

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [87]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


Aggregates:

In [88]:
x = np.arange(1, 8)
print(x)
np.add.reduce(x)

[1 2 3 4 5 6 7]


28

In [89]:
np.multiply.reduce(x)

5040

In [90]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [91]:
np.multiply.accumulate(x)

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)